// 公共
export const SWITCH_SIDEBAR_COLLAPSE = 'SWITCH_SIDEBAR_COLLAPSE' // 折叠菜单
export const UPDATE_DOCUMENT_CLIENT_HEIGHT = 'UPDATE_DOCUMENT_CLIENT_HEIGHT' // 更新页面高度
export const UPDATE_DOCUMENT_CLIENT_IFRAME = 'UPDATE_DOCUMENT_CLIENT_IFRAME' // 获取高度
export const UPDATE_MENU_NAV_LIST = 'UPDATE_MENU_NAV_LIST' // 更新菜单列表
export const ADD_CONTENT_TAB = 'ADD_CONTENT_TAB' // 添加Tab
export const UPDATE_CONTENT_TABS = 'UPDATE_CONTENT_TABS' // 更新Tab
export const DELETE_CONTENT_TABS = 'DELETE_CONTENT_TABS' // 删除
export const UPDATE_CONTENT_TABS_ACTIVE_NAME = 'UPDATE_CONTENT_TABS_ACTIVE_NAME' // 点击某一个TabName
export const UPDATE_CONTENT_TABS_ACTIVE = 'UPDATE_CONTENT_TABS_ACTIVE' // 获取当前活跃的Tab
// 用户
export const UPDATE_USER_ID = 'UPDATE_USER_ID'
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
